- hosts: 127.0.0.1
  connection: local
  tasks:
  - apt: name=python-httplib2 update_cache=yes
  - apt: name=vim 
  - apt: name=ruby 
  - apt: name=gcc
  - apt: name=make
  - apt: name=python 
  - apt: name=python-pip
  - apt: name=python-dev
  - apt: name=ruby1.9.1-dev
  - gem: name=fpm state=latest
  - gem: name=jekyll state=latest
  - name: Add core users.
    user: name={{ item }} shell=/bin/bash groups=admin state=present
    with_items: 
      - jedwards
      - bob



