- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: install httplib 
     apt: name=httplib2 update_cache=yes
  - name: install vim 
     apt: name=vim 
  - name: install ruby 
     apt: name=ruby 
  - name: install fpm
     gem: name=fpm 






